name: Node.js CI

on:
  push:
    branches:
      - devs

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['frontend', 'backend']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.7.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.7.0'
          cache: 'npm'

      - name: Install dependencies for ${{ matrix.directory }}
        run: |
          cd ${{ matrix.directory }}
          npm install

      - name: Build ${{ matrix.project }} (if build script is present)
        run: |
          cd ${{ matrix.project }}
          if [ -f package.json ]; then
            if grep -q '"build":' package.json; then
              npm run build
            fi
          fi

      - name: Config Github Setting
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push to main (if this step is necessary)
        if: success() && github.ref == 'refs/heads/devs'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          atomic: true
